#!/usr/bin/env python3
"""One-time migration: put a space between a table's section name and its number.

Idempotent -- running it twice is harmless.

A table's organizer-facing name is its section plus its number within that section, and it was
built by concatenation: ``"Front Row" + "1"`` reads "Front Row1" everywhere a table is named.
``datatypes.table_code_for`` is now the one place that builds it, with a separator.

That string is not only a label. It is the key the tables grid matches a stored assignment
against (``derive_market_table_rows``) and the code check-in reads, so a market assigned by the
old build would have every one of its placements fall off the freshly derived grid and reappear
as a duplicate row for a table that does not exist. Hence this: the stored codes are brought to
the same spelling the code now computes.

The split is decided by the market's OWN sections, not by a regular expression. A section may
end in a digit ("Hall 2"), so "Hall 21" is ambiguous in isolation -- it is table 1 of "Hall 2"
or table 21 of "Hall"; only the market's section list says which. Longest name first, so a
market holding both "Hall" and "Hall 2" resolves to the more specific one. A code no section
claims is left exactly as it was: an unrecognized code is a code this migration cannot rewrite
safely, and leaving it alone keeps the document readable rather than inventing a placement.

Usage:
    python migrations/migrate_table_code_separator.py
    python migrations/migrate_table_code_separator.py --dry-run
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datatypes import table_code_for
from db_config import get_database


def rewritten_code(code, section_names):
    """The separated spelling of one stored table code, or None when it needs no change.

    Returns None both for a code already in the new form and for one no section claims, because
    the caller does the same thing with either: leave it alone.
    """
    text = str(code or "")
    for name in sorted(section_names, key=len, reverse=True):
        if not name or not text.startswith(name):
            continue
        remainder = text[len(name):]
        if remainder.isdigit():
            return table_code_for(name, int(remainder))
    return None


def _migrated_market(document):
    """The market's placements and unassigned-table entries with their codes separated.

    Returns ``(changes, count)`` as a ``$set`` map addressed by array index, so a concurrent
    write to any other part of the document survives. An empty map means nothing to do.
    """
    setup = document.get("setupObject") or {}
    section_names = [
        str(section.get("name") or "")
        for section in (setup.get("sections") or [])
        if isinstance(section, dict)
    ]
    if not section_names:
        return {}, 0

    changes = {}
    assignment = document.get("assignmentObject") or {}

    for index, placement in enumerate(assignment.get("vendorAssignments") or []):
        if not isinstance(placement, dict):
            continue
        separated = rewritten_code(placement.get("tableCode"), section_names)
        if separated is not None:
            changes[f"assignmentObject.vendorAssignments.{index}.tableCode"] = separated

    # Derived, and regenerated by the next assignment run - but a document left half-rewritten
    # reads as though the two halves disagree, and anything reporting from it would say so.
    statistics = assignment.get("assignmentStatistics") or {}
    for date, entries in (statistics.get("unassignedTables") or {}).items():
        if not isinstance(entries, list):
            continue
        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                continue
            separated = rewritten_code(entry.get("tableCode"), section_names)
            if separated is not None:
                path = f"assignmentObject.assignmentStatistics.unassignedTables.{date}.{index}"
                changes[f"{path}.tableCode"] = separated

    return changes, len(changes)


def migrate(db, dry_run=False):
    collection = db.markets

    markets = 0
    codes = 0
    for document in collection.find({"assignmentObject.vendorAssignments.0": {"$exists": True}}):
        changes, count = _migrated_market(document)
        if not changes:
            continue
        markets += 1
        codes += count
        if dry_run:
            sample = next(iter(changes.items()))
            print(
                f"[DRY RUN] market {document.get('id')}: {count} table code(s), "
                f"e.g. {sample[0]} -> {sample[1]!r}"
            )
            continue
        collection.update_one({"_id": document["_id"]}, {"$set": changes})

    prefix = "DRY RUN: would update" if dry_run else "Updated"
    print(f"{prefix} {codes} table code(s) across {markets} market(s)")
    if markets == 0:
        print("Every stored table code already carries its separator.")


def main():
    parser = argparse.ArgumentParser(
        description="Separate section name from table number in every stored table code"
    )
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without applying")
    args = parser.parse_args()

    migrate(get_database(), dry_run=args.dry_run)


if __name__ == "__main__":
    main()
